favicon: isolated-monochrome-white.png
logo: isolated-monochrome-white.svg
title: Media Cloud AI
description: The cloud platform to run AI on media content.
google_analytics:
theme: jekyll-theme-cayman
